swagger: "2.0"
info:
  version: "0.0.1"
  title: Yet another simple tool to manipulate your Amazon Cognito user pools
host: localhost:8080
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /token/{userPoolId}/{clientId}:
    x-swagger-router-controller: token
    get:
      description: Get a Cognito id token
      operationId: get_id_token
      parameters:
        - name: userPoolId
          in: path
          description: The user pool Id
          required: true
          type: string
        - name: clientId
          in: path
          description: The client Id
          required: true
          type: string
        - name: user
          in: query
          description: The user name
          required: true
          type: string
        - name: password
          in: query
          description: The password
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/tokenResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /changePassword/{userPoolId}/{clientId}:
      x-swagger-router-controller: changePassword
      get:
        description: Get a Cognito id token
        operationId: post_change_password
        parameters:
          - name: userPoolId
            in: path
            description: The user pool Id
            required: true
            type: string
          - name: clientId
            in: path
            description: The client Id
            required: true
            type: string
          - name: user
            in: query
            description: The user name
            required: true
            type: string
          - name: oldPassword
            in: query
            description: The password
            required: true
            type: string
          - name: newPassword
            in: query
            description: The password
            required: true
            type: string
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/tokenResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  tokenResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
